import assert from "node:assert/strict";
import test from "node:test";
import { chunkPages, normalizeText } from "../lib/rag/chunking.ts";
import { mapCitations } from "../lib/rag/citations.ts";
import { hasSufficientEvidence, NO_ANSWER } from "../lib/rag/grounding.ts";
import { filterRetrievedChunks } from "../lib/rag/retrieval.ts";
import { feedbackSchema, questionSchema, validatePdf } from "../lib/validation.ts";

test("normalizes and chunks pages while retaining page references",()=>{const pages=[{pageNumber:7,text:`  Section one.   ${"Evidence sentence. ".repeat(90)}`}];const chunks=chunkPages(pages,400,60);assert.ok(chunks.length>1);assert.ok(chunks.every(c=>c.pageNumber===7));assert.deepEqual(chunks.map(c=>c.chunkIndex),chunks.map((_,i)=>i));assert.equal(normalizeText("a   b\n\n\n\nc"),"a b\n\nc")});
test("rejects invalid upload types and oversized PDFs",()=>{assert.equal(validatePdf({name:"manual.txt",type:"text/plain",size:20}).ok,false);assert.equal(validatePdf({name:"manual.pdf",type:"application/pdf",size:21*1024*1024}).ok,false);assert.equal(validatePdf({name:"manual.pdf",type:"application/pdf",size:1024}).ok,true)});
test("validates questions and feedback",()=>{assert.equal(questionSchema.safeParse({question:"Where is the rule?"}).success,true);assert.equal(questionSchema.safeParse({question:"x"}).success,false);assert.equal(feedbackSchema.safeParse({messageId:"bad",rating:"helpful"}).success,false)});
test("retrieval enforces ownership, threshold, score order and limit",()=>{const chunks=[{id:"a",documentId:"owned",documentName:"A",pageNumber:1,content:"A long supporting passage with direct evidence for the question.",similarity:.82},{id:"b",documentId:"other",documentName:"B",pageNumber:1,content:"Other user evidence must not leak into results.",similarity:.99},{id:"c",documentId:"owned",documentName:"A",pageNumber:2,content:"Low score",similarity:.4}];const result=filterRetrievedChunks(chunks,new Set(["owned"]),.78,6);assert.deepEqual(result.map(c=>c.id),["a"])});
test("no-answer guard refuses insufficient evidence",()=>{assert.equal(hasSufficientEvidence([]),false);assert.equal(hasSufficientEvidence([{id:"a",documentId:"d",documentName:"Doc",pageNumber:1,content:"short",similarity:.95}]),false);assert.match(NO_ANSWER,/enough information/i)});
test("citation mapping is deterministic and removes duplicate pages",()=>{const chunks=[{id:"a",documentId:"d",documentName:"Rules",pageNumber:4,content:"one",similarity:.9},{id:"b",documentId:"d",documentName:"Rules",pageNumber:4,content:"two",similarity:.88},{id:"c",documentId:"d",documentName:"Rules",pageNumber:8,content:"three",similarity:.84}];const citations=mapCitations(chunks);assert.equal(citations.length,2);assert.deepEqual(citations.map(c=>c.number),[1,2]);assert.deepEqual(citations.map(c=>c.pageNumber),[4,8])});
