"use client";
import { BookOpen, Check, ChevronDown, FileText, MessageSquarePlus, Send, ThumbsDown, ThumbsUp } from "lucide-react";
import { useState } from "react";
import { documents, retrievedSources } from "../lib/demo-data";
import { PageHeader } from "./page-header";

type Message = { question: string; answer: string; noAnswer?: boolean };
const examples = ["What are the requirements for a valid restart?", "Who completes the venue safety inspection?", "How long is the appeal window?"];
export function AskView() {
  const [question,setQuestion]=useState(""); const [messages,setMessages]=useState<Message[]>([]); const [loading,setLoading]=useState(false); const [scope,setScope]=useState("all"); const [feedback,setFeedback]=useState<"helpful"|"incorrect"|null>(null); const [comment,setComment]=useState(""); const [submitted,setSubmitted]=useState(false);
  function ask(value=question){ const q=value.trim(); if(!q||loading)return; setQuestion("");setLoading(true);setFeedback(null);setSubmitted(false);queueMicrotask(()=>{const unknown=/parking|weather|salary/i.test(q);setMessages(m=>[...m,{question:q,answer:unknown?"I couldn’t find enough information in the selected documents to answer this reliably.":"No. The player taking the restart may not touch the ball again until another player has touched it.",noAnswer:unknown}]);setLoading(false)}) }
  return <main className="dashboard-page ask-page"><PageHeader eyebrow="GROUNDED Q&A" title="Ask your documents" description="Get concise answers supported by exact source pages." actions={<button className="secondary-button"><MessageSquarePlus size={16}/> New conversation</button>}/>
    <div className="ask-layout"><section className="chat-surface">
      <div className="scope-bar"><span>SEARCHING</span><label><BookOpen size={16}/><select value={scope} onChange={e=>setScope(e.target.value)} aria-label="Documents to search"><option value="all">All ready documents</option>{documents.filter(d=>d.status==="Ready").map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select><ChevronDown size={14}/></label><small>{scope==="all"?"3 documents · 358 searchable chunks":"1 selected document"}</small></div>
      {!messages.length && !loading ? <div className="ask-empty"><span className="ask-empty-icon"><BookOpen/></span><h2>What would you like to verify?</h2><p>RuleWise will search the selected documents and show the evidence behind its answer.</p><div className="example-questions">{examples.map(e=><button key={e} onClick={()=>ask(e)}>{e}<span>→</span></button>)}</div></div> : <div className="conversation">{messages.map((m,i)=><div className="message-group" key={`${m.question}-${i}`}><div className="user-message"><span>YOU</span><p>{m.question}</p></div><article className={m.noAnswer?"assistant-message no-answer":"assistant-message"}><header><span className="answer-icon">R</span><b>RuleWise</b><small>{m.noAnswer?"INSUFFICIENT EVIDENCE":"GROUNDED IN 2 SOURCES"}</small></header><p>{m.answer}</p>{!m.noAnswer&&<div className="inline-citations">{retrievedSources.map(s=><button key={s.id}><span>{s.id}</span>{s.document} · p. {s.page}</button>)}</div>}<footer><span>Was this answer useful?</span><button className={feedback==="helpful"&&i===messages.length-1?"selected":""} onClick={()=>setFeedback("helpful")}><ThumbsUp size={14}/> Helpful</button><button className={feedback==="incorrect"&&i===messages.length-1?"selected":""} onClick={()=>setFeedback("incorrect")}><ThumbsDown size={14}/> Incorrect</button></footer>{i===messages.length-1&&feedback==="incorrect"&&!submitted&&<div className="feedback-form"><label htmlFor="feedback-comment">What was wrong with this answer? <span>Optional</span></label><textarea id="feedback-comment" value={comment} onChange={e=>setComment(e.target.value)} placeholder="The cited section does not address…"/><div><button onClick={()=>setFeedback(null)}>Cancel</button><button className="primary-button" onClick={()=>setSubmitted(true)}>Submit feedback</button></div></div>}{i===messages.length-1&&submitted&&<div className="feedback-thanks"><Check size={15}/> Feedback saved. Thank you.</div>}</article></div>)}{loading&&<div className="searching-state" role="status"><span className="search-pulse"/><div><b>Searching your documents</b><small>Finding the strongest supporting evidence…</small></div></div>}</div>}
      <form className="ask-composer" onSubmit={e=>{e.preventDefault();ask()}}><label htmlFor="question" className="sr-only">Ask a question</label><textarea id="question" placeholder="Ask a question about your documents…" value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}}/><button disabled={!question.trim()||loading} aria-label="Send question"><Send size={17}/></button><small>Enter to send · Shift + Enter for a new line</small></form>
    </section><aside className="evidence-rail"><div className="evidence-heading"><p className="page-eyebrow">EVIDENCE</p><h2>Retrieved sources</h2><p>The closest matching passages for the latest answer.</p></div>{messages.length&&!messages.at(-1)?.noAnswer?retrievedSources.map(s=><article key={s.id} className="evidence-card"><header><span>{s.id}</span><div><b>{s.document}</b><small>Page {s.page} · {s.section}</small></div><FileText size={16}/></header><blockquote>“{s.excerpt}”</blockquote><footer><span>Similarity</span><b>{s.score.toFixed(3)}</b></footer></article>):<div className="evidence-empty"><FileText/><p>Sources will appear here after you ask a question.</p></div>}</aside></div>
  </main>;
}
